### ISSUE TITLE
Installed but doesn't run

### ISSUE THREAD

**Issue by ajkothari13** [autolume/autolux#13]
Hi. I guess it is not supported on Ubuntu 17.10, is it? It installed without any error but on running in terminal it says  - "autolux: command not found"

**Comment by okayzed** [comment]
This is a good question. Can you check where autolux was installed? On ubuntu 16.04, pip placed the binaries into /usr/local/bin/autolux for me. If it does the same, you need to have /usr/local/bin in your $PATH

**Comment by ajkothari13** [comment]
Hello. The binary is present only in home/(username)/.local/bin
I opened terminal there and executed "autolux" --> command not found
Then did something else:
any idea what's going on?

---------------------------------

v@pc:~/.local/bin$ python2.7 autolux
DAEMON MODE: False
CROPPING: True
FADE TIME: 800
SLEEP TIME: 1200
DISPLAY RANGE: 5 20
LEARNING MODE: True
BRIGHTNESS RANGE: 5000 50000
RECALIBRATE EVERY: 60000
FOLLOW WINDOW PID: False
FOLLOW WINDOW TITLE: True
SCREENSHOT CMD import -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
LOADING LUMA MAP /home/v/.config/autolux/luma_map.p
WARNING: NOT LOADING LUMA MAP [Errno 2] No such file or directory: '/home/v/.config/autolux/luma_map.p'
MODEL|TS:1519835869, LUMA:26000, NEW GAMMA:0.42, NEW BRIGHTNESS: 11/20
Traceback (most recent call last):
  File "autolux", line 4, in <module>
    autolux.run()
  File "/home/v/.local/lib/python2.7/site-packages/autolux/autolux.py", line 198, in run
    monitor_luma()
  File "/home/v/.local/lib/python2.7/site-packages/autolux/autolux.py", line 165, in monitor_luma
    run_cmd("xbacklight -set %s -time %s" % (new_level, opts.TRANSITION_MS / 2))
  File "/home/v/.local/lib/python2.7/site-packages/autolux/autolux.py", line 20, in run_cmd
    ret = subprocess.check_output(args)
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by okayzed** [comment]
it looks like you've managed to run autolux :-D i think the next error is that you don't have "xbacklight" installed (or in your path). there are some dependencies listed in the README: xdolight, xbacklight, imagemagick (and python bindings), etc.

re: PATH: it looks like pip is putting your python binaries in ~/.local/bin. to add this location to your PATH, use `export PATH=${PATH}:~/.local/bin` in your .bashrc or other shell init file so that you can call `autolux` directly

**Comment by ajkothari13** [comment]
Thanks a ton, man. And my apologies for not giving attention to the dependencies. Not sure how I missed them.
