### ISSUE TITLE
Is it not working, again?

### ISSUE THREAD

**Issue by ajkothari13** [autolume/autolux#14]
Is this ending with some error?

>DAEMON MODE: False
>CROPPING: True
>FADE TIME: 800
>SLEEP TIME: 1200
>DISPLAY RANGE: 5 20
>LEARNING MODE: True
>BRIGHTNESS RANGE: 5000 50000
>RECALIBRATE EVERY: 60000
>FOLLOW WINDOW PID: False
>FOLLOW WINDOW TITLE: True
>SCREENSHOT CMD import -colorspace gray -screen -w root -quality 20 -crop 10x100%+400+0
>LOADED 6 LUMA OBSERVATIONS
>LOADING LUMA MAP /home/v/.config/autolux/luma_map.p
>TIME MAP IS 28% COMPLETE, LUMA MAP IS 23% COMPLETE
>MODEL|TS:1519876875, LUMA:10500, NEW GAMMA:0.77, NEW BRIGHTNESS: 17/20
>No outputs have backlight property
>Traceback (most recent call last):
>  File "/home/v/.local/bin/autolux", line 4, in <module>
>    autolux.run()
>  File "/home/v/.local/lib/python2.7/site-packages/autolux/autolux.py", line 198, in run
>    monitor_luma()
>  File "/home/v/.local/lib/python2.7/site-packages/autolux/autolux.py", line 165, in monitor_luma
>    run_cmd("xbacklight -set %s -time %s" % (new_level, opts.TRANSITION_MS / 2))
>  File "/home/v/.local/lib/python2.7/site-packages/autolux/autolux.py", line 20, in run_cmd
>    ret = subprocess.check_output(args)
>  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
>    raise CalledProcessError(retcode, cmd, output=output)
>subprocess.CalledProcessError: Command '['xbacklight', '-set', '17.0', '-time', '400']' returned non-zero exit >status 1

**Comment by okayzed** [comment]
`"No outputs have backlight property"` is the error message i am seeing in your output. 

try running: `xbacklight -set 17.0 -time 400`  and seeing what happens - it should hopefully give you the same error

**Comment by ajkothari13** [comment]
ok, from askubuntu i got this:

>sudo find /sys/ -type f -iname '*brightness*'

and that command gives a lot of options. Also I see that below location has 2 directories
> /sys/class/backlight

I don't know what to link where and how. It's totally understandable if this is not your area to be bothered about. In which case, unfortunately no autolux for me.

Thanks for your time and patience, though. 
[(This is askubuntu link which informed about all the above)](https://askubuntu.com/questions/715306/xbacklight-no-outputs-have-backlight-property-no-sys-class-backlight-folder)

**Comment by okayzed** [comment]
i don't mind. you can ping me on oky on freenode IRC if you want real-time help. 

are you using a laptop or desktop? i looked at the advice in that link and tried it on my machine and am not able to follow it (create a symlink like they suggest), but i have some idea of what is going wrong

**Comment by okayzed** [comment]
I added a commit with some commands to use xrandr based dimming. Please try it out  - to do so, you can git clone the repo, then run `python autolux/autolux.py --xrandr HDMI-1`

the README.md has updated notes on how to use --xrandr option and how to also use --reset and --adjust alongside it. the scale is from 30 - 100 (if 30 is not dim enough, we can lower it to 10 or 20).

 notice that you can adjust your external monitor's brightness with: `python autolux/autolux.py --xrandr HDMI-1 --adjust +10` and reset it back to normal with the --reset flag. You can bind these to your keyboard brightness up / down keys. As you  adjust the brightness with different windows displayed, autolux should learn your preferences over time. 

the one downside (atm) to xrandr is that the dimming is not gradual, it happens immediately, but that can potentially be added.

**Comment by ajkothari13** [comment]
Installed your tool and it is working. Going to find out how to bind the command to keyboard's keys now. Dimming is not gradual but it doesn't matter :) :+1: 

Edit:
So, 
1. I have binded the keys
2. Reduced steps to increase/decrease from 10 to 1
On my way to see how the program behaves now 
Please let me know if there's anything you need from my end
And, THANKS :+1:

**Comment by okayzed** [comment]
awesome, glad it works and thanks for testing! I'll push the current version to pypi (so it can be installed with pip)

**Comment by ajkothari13** [comment]
Thanks to you!
