### ISSUE TITLE
Cannot run at startup

### ISSUE THREAD

**Issue by ramottamado** [autolume/autolux#4]
I'm using Ubuntu 16.04, installing autolux with `pip2 install --user autolux`, I can run autolux from terminal but when I try to add autolux to startup, autolux doesn't run.

**Comment by okayzed** [comment]
it's possible that you need to specify the full bin path for autolux in your startup environment. for example, if autolux was installed into ~/local/bin, you should use `~/local/bin/autolux` as the startup command. 

are there any further logs you can add?

**Comment by ramottamado** [comment]
Thanks! Your solution worked, I'm now marking this as closed.
