### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by gutierri** [autolume/autolux#6]
It's GPLv3+?

ref: https://github.com/autolume/autolux/blob/master/autolux/xbacklight.py#L6

**Comment by okayzed** [comment]
that GPLv3+ note is from the xbacklight code. i am open to any license, but had originally placed autolux  under MIT (https://github.com/autolume/autolux/blob/master/setup.py#L14). i don't know how the licenses interact

**Comment by gutierri** [comment]
@okayzed I know ... read the comment (xbacklight). The GPL allows branching and distributing the same terms (freedoms). But you have part of your code with GPL, I do not know if it is interesting to do the license exchange.

ref: https://www.gnu.org/licenses/gpl-howto.html.en

**Comment by okayzed** [comment]
what is the least effort action for me to take? if you make a pull request with a LICENSE file or advise on which to use, i can do it (i don't mind GPLv3 vs MIT)

**Comment by gutierri** [comment]
OK. I will send references soon on a GPLv3 and MIT. And I can make the Pull
Request,
