### ISSUE TITLE
Only one process

### ISSUE THREAD

**Issue by gutierri** [autolume/autolux#9]
It is possible to run more than one autolux process, it would be interesting to fire an exception when you have more than one.

What do you think?

**Comment by okayzed** [comment]
sounds good to me. if you want to put up a diff, please do (or let me know if you want me to). personally, i have an alias in my bash:

    function run_if_not { 
      pgrep -f $1 || $* 
    } 

and do: `run_if_not autolux` in my startup scripts, but daemonizing autolux couldn't hurt

**Comment by gutierri** [comment]
It would be good to manage this no software, what do you think?

**Comment by okayzed** [comment]
87b1a46 adds support for --daemon flag. You need to install python-daemon (via pip or apt) to use it

**Comment by gutierri** [comment]
@okayzed I will put instructions on this without README.

**Comment by okayzed** [comment]
Are you saying you'll update the readme? if so, thanks! i pushed 0.0.30 to pypi, so you can update it with pip (if you want to try it out).

**Comment by gutierri** [comment]
@okayzed Yes... I'm update readme.
